# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormParams(object):
    def setupUi(self, FormParams):
        FormParams.setObjectName("FormParams")
        FormParams.resize(691, 595)
        self.line = QtWidgets.QFrame(FormParams)
        self.line.setGeometry(QtCore.QRect(10, 260, 661, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.paramBox = QtWidgets.QGroupBox(FormParams)
        self.paramBox.setGeometry(QtCore.QRect(30, 90, 281, 171))
        self.paramBox.setObjectName("paramBox")
        self.checkTRL = QtWidgets.QCheckBox(self.paramBox)
        self.checkTRL.setGeometry(QtCore.QRect(20, 20, 231, 17))
        self.checkTRL.setObjectName("checkTRL")
        self.checkTRL.setChecked(True)
        self.checkMRL = QtWidgets.QCheckBox(self.paramBox)
        self.checkMRL.setGeometry(QtCore.QRect(20, 50, 231, 17))
        self.checkMRL.setObjectName("checkMRL")
        self.checkMRL.setChecked(True)
        self.checkERL = QtWidgets.QCheckBox(self.paramBox)
        self.checkERL.setGeometry(QtCore.QRect(20, 80, 231, 17))
        self.checkERL.setObjectName("checkERL")
        self.checkERL.setChecked(True)
        self.checkORL = QtWidgets.QCheckBox(self.paramBox)
        self.checkORL.setGeometry(QtCore.QRect(20, 110, 231, 17))
        self.checkORL.setObjectName("checkORL")
        self.checkORL.setChecked(True)
        self.checkCRL = QtWidgets.QCheckBox(self.paramBox)
        self.checkCRL.setGeometry(QtCore.QRect(20, 140, 231, 17))
        self.checkCRL.setObjectName("checkCRL")
        self.checkCRL.setChecked(True)
        self.typeBox = QtWidgets.QGroupBox(FormParams)
        self.typeBox.setGeometry(QtCore.QRect(380, 90, 281, 111))
        self.typeBox.setObjectName("typeBox")
        self.radio_hard = QtWidgets.QRadioButton(self.typeBox)
        self.radio_hard.setGeometry(QtCore.QRect(10, 20, 211, 17))
        self.radio_hard.setObjectName("radio_hard")
        self.radio_hard.setChecked(True)
        self.radio_soft = QtWidgets.QRadioButton(self.typeBox)
        self.radio_soft.setGeometry(QtCore.QRect(10, 50, 261, 17))
        self.radio_soft.setObjectName("radio_soft")
        self.radio_both = QtWidgets.QRadioButton(self.typeBox)
        self.radio_both.setGeometry(QtCore.QRect(10, 80, 261, 16))
        self.radio_both.setAutoRepeat(False)
        self.radio_both.setObjectName("radio_both")
        self.set_params = QtWidgets.QPushButton(FormParams)
        self.set_params.setGeometry(QtCore.QRect(430, 210, 181, 31))
        self.set_params.setObjectName("set_params")
        self.labelCalc = QtWidgets.QLabel(FormParams)
        self.labelCalc.setGeometry(QtCore.QRect(70, 10, 591, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCalc.setFont(font)
        self.labelCalc.setTextFormat(QtCore.Qt.RichText)
        self.labelCalc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCalc.setWordWrap(True)
        self.labelCalc.setObjectName("labelCalc")
        self.labelProject = QtWidgets.QLabel(FormParams)
        self.labelProject.setGeometry(QtCore.QRect(10, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelProject.setFont(font)
        self.labelProject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProject.setObjectName("labelProject")
        self.frameGraph = QtWidgets.QFrame(FormParams)
        self.frameGraph.setGeometry(QtCore.QRect(370, 300, 291, 271))
        self.frameGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraph.setObjectName("frameGraph")
        self.ugtSlider = QtWidgets.QSlider(FormParams)
        self.ugtSlider.setGeometry(QtCore.QRect(70, 400, 291, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ugtSlider.setFont(font)
        self.ugtSlider.setTabletTracking(False)
        self.ugtSlider.setAutoFillBackground(False)
        self.ugtSlider.setMaximum(9)
        self.ugtSlider.setPageStep(10)
        self.ugtSlider.setProperty("value", 0)
        self.ugtSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ugtSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.ugtSlider.setTickInterval(0)
        self.ugtSlider.setObjectName("ugtSlider")
        self.label_shkala = QtWidgets.QLabel(FormParams)
        self.label_shkala.setGeometry(QtCore.QRect(70, 370, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_shkala.setFont(font)
        self.label_shkala.setObjectName("label_shkala")
        self.label_ugt = QtWidgets.QLabel(FormParams)
        self.label_ugt.setGeometry(QtCore.QRect(20, 380, 47, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_ugt.setFont(font)
        self.label_ugt.setObjectName("label_ugt")
        self.trl = QtWidgets.QLabel(FormParams)
        self.trl.setGeometry(QtCore.QRect(60, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trl.setFont(font)
        self.trl.setObjectName("trl")
        self.mrl = QtWidgets.QLabel(FormParams)
        self.mrl.setGeometry(QtCore.QRect(120, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mrl.setFont(font)
        self.mrl.setObjectName("mrl")
        self.crl = QtWidgets.QLabel(FormParams)
        self.crl.setGeometry(QtCore.QRect(300, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crl.setFont(font)
        self.crl.setObjectName("crl")
        self.orl = QtWidgets.QLabel(FormParams)
        self.orl.setGeometry(QtCore.QRect(240, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.orl.setFont(font)
        self.orl.setObjectName("orl")
        self.erl = QtWidgets.QLabel(FormParams)
        self.erl.setGeometry(QtCore.QRect(180, 450, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.erl.setFont(font)
        self.erl.setObjectName("erl")
        self.labelNumProject = QtWidgets.QLabel(FormParams)
        self.labelNumProject.setGeometry(QtCore.QRect(180, 300, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelNumProject.setFont(font)
        self.labelNumProject.setText("")
        self.labelNumProject.setObjectName("labelNumProject")
        self.trl_result = QtWidgets.QLabel(FormParams)
        self.trl_result.setGeometry(QtCore.QRect(60, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trl_result.setFont(font)
        self.trl_result.setText("")
        self.trl_result.setObjectName("trl_result")
        self.mrl_result = QtWidgets.QLabel(FormParams)
        self.mrl_result.setGeometry(QtCore.QRect(120, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mrl_result.setFont(font)
        self.mrl_result.setText("")
        self.mrl_result.setObjectName("mrl_result")
        self.erl_result = QtWidgets.QLabel(FormParams)
        self.erl_result.setGeometry(QtCore.QRect(180, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.erl_result.setFont(font)
        self.erl_result.setText("")
        self.erl_result.setObjectName("erl_result")
        self.orl_result = QtWidgets.QLabel(FormParams)
        self.orl_result.setGeometry(QtCore.QRect(240, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.orl_result.setFont(font)
        self.orl_result.setText("")
        self.orl_result.setObjectName("orl_result")
        self.crl_result = QtWidgets.QLabel(FormParams)
        self.crl_result.setGeometry(QtCore.QRect(300, 470, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.crl_result.setFont(font)
        self.crl_result.setText("")
        self.crl_result.setObjectName("crl_result")

        self.retranslateUi(FormParams)
        QtCore.QMetaObject.connectSlotsByName(FormParams)

    def retranslateUi(self, FormParams):
        _translate = QtCore.QCoreApplication.translate
        FormParams.setWindowTitle(_translate("FormParams", "Form"))
        self.paramBox.setTitle(_translate("FormParams", "Параметры оценки"))
        self.checkTRL.setText(_translate("FormParams", "Технологическая готовность (TRL)"))
        self.checkMRL.setText(_translate("FormParams", "Производственная готовность (MRL)"))
        self.checkERL.setText(_translate("FormParams", "Инженерная готовность (ERL)"))
        self.checkORL.setText(_translate("FormParams", "Организационная готовность (ORL)"))
        self.checkCRL.setText(_translate("FormParams", "Коммерческая готовность (СRL)"))
        self.typeBox.setTitle(_translate("FormParams", "Тип проекта"))
        self.radio_hard.setText(_translate("FormParams", "Разработка оборудования"))
        self.radio_soft.setText(_translate("FormParams", "Разработка программного обеспечения"))
        self.radio_both.setText(_translate("FormParams", "Разработка оборудования и ПО"))
        self.set_params.setText(_translate("FormParams", "Установить параметры"))
        self.labelCalc.setText(_translate("FormParams", "Калькулятор уровня готовности технологий для оценки зрелости инновационного продукта/технологии к внедрению в ОАО «РЖД»"))
        self.labelProject.setText(_translate("FormParams", "Номер проекта"))
        self.label_shkala.setText(_translate("FormParams", "0    1    2    3    4    5    6    7    8    9"))
        self.label_ugt.setText(_translate("FormParams", "УГТ"))
        self.trl.setText(_translate("FormParams", "TRL"))
        self.mrl.setText(_translate("FormParams", "MRL"))
        self.crl.setText(_translate("FormParams", "CRL"))
        self.orl.setText(_translate("FormParams", "ORL"))
        self.erl.setText(_translate("FormParams", "ERL"))
